### PR TITLE
Improving typespecs v1

### PR DESCRIPTION
**Pull request by Fl4m3Ph03n1x**
A few things were done here. I did this PR a small one on purpose. 

- I fixed the `Phoenix.LiveView.Rendered` to `Phoenix.LiveView.Rendered.t()` because I am an idiot and forgot the `.t()` part.
- I removed several case clauses that were never going to be executed. Now this part can be a little bit controversial. I understand why those were there (even if they were never going to be executed), they were there to prevent error cases. because of the nature of the calls being made, the only way to prevent failure would be to use a `try/rescue` . I have not done this to maintain the original behavior of the code, but there is an argument here to be had if you wish.

I am not adding typespecs for now, I am simply trying to fix some of the "low hanging fruit" issues that dialyzer picks up (even without the help of types).

### CODE REVIEW

**Comment by dominicletz** [comment]
Thanks, @Fl4m3Ph03n1x I've merged the other branch and I think I did get cover all your changes there as well. Let me know if we can close this or if there are other changes you can think of.

Cheers!

**Comment by Fl4m3Ph03n1x** [comment]
There is one small change missing. 

In `lib/desktop/menu.ex`, line 128:

From:
```
@callback render(Keyword.t()) :: Phoenix.LiveView.Rendered
```

To:
```
@callback render(Keyword.t()) :: Phoenix.LiveView.Rendered.t()
```

I will update my branch and ask for another review once I have some time.

**Comment by Fl4m3Ph03n1x** [comment]
Conflicts fixed. 
Please review/approve when convenient :D

**Comment by Fl4m3Ph03n1x** [comment]
Yey!
One final question, would these fixes perhaps merit the release of a new version 1.4.X?

**Comment by dominicletz** [comment]
Sure

**Comment by dominicletz** [comment]
Done

**Pull request merged**
